# This file was generated by AI and is not subject to copyright protection.
# It is dedicated to the public domain.

# CMake configuration for building proot for Termux (Android terminal)
# Termux uses Android NDK but provides a Linux-like environment

include(ExternalProject)

# For Termux builds, we use the Android NDK toolchain
# Termux typically runs on arm64-v8a or x86_64

set(PROOT_SRC ${CMAKE_CURRENT_BINARY_DIR}/proot-prefix/src/proot/src)
set(PROOT_BIN ${CMAKE_CURRENT_BINARY_DIR}/proot-prefix/src/proot-build)

if(ANDROID)
    # Building for Android/Termux
    include(Talloc)
    include(Unwind)
    
    set(PROOT_C_FLAGS "-I${TALLOC_INCLUDE_DIRS} -I${PROOT_SRC} -D_GNU_SOURCE -I${UNWIND_INCLUDE_DIRS}")
    set(PROOT_LINKER_FLAGS "-L${TALLOC_BIN}/lib -L${CMAKE_BINARY_DIR} -ltalloc -lunwind_ptrace")
    
    # Get API level from ANDROID_PLATFORM (format: android-XX) or fall back to 24
    if(ANDROID_PLATFORM)
        string(REGEX REPLACE "android-" "" ANDROID_API_LEVEL "${ANDROID_PLATFORM}")
    else()
        set(ANDROID_API_LEVEL 24)
    endif()
    
    # Select correct clang target based on architecture
    if(${CMAKE_ANDROID_ARCH_ABI} STREQUAL "arm64-v8a")
        set(PROOT_C_COMPILER ${ANDROID_TOOLCHAIN_ROOT}/bin/aarch64-linux-android${ANDROID_API_LEVEL}-clang)
    elseif(${CMAKE_ANDROID_ARCH_ABI} STREQUAL "x86_64")
        set(PROOT_C_COMPILER ${ANDROID_TOOLCHAIN_ROOT}/bin/x86_64-linux-android${ANDROID_API_LEVEL}-clang)
    else()
        set(PROOT_C_COMPILER ${ANDROID_TOOLCHAIN_ROOT}/bin/${CMAKE_ANDROID_ARCH_ABI}-linux-android${ANDROID_API_LEVEL}-clang)
    endif()
    
    ExternalProject_Add(
        proot-termux
        GIT_REPOSITORY https://github.com/Ananbox/proot.git
        GIT_TAG a8189b1e6fb892104fdc01a939c7e75e9325a3c0
        GIT_SHALLOW 1
        CONFIGURE_COMMAND cd ${PROOT_SRC} && make clean || true
        BUILD_COMMAND cd ${PROOT_SRC} && make V=1 CC=${PROOT_C_COMPILER} LD=${PROOT_C_COMPILER} STRIP=${CMAKE_STRIP} OBJCOPY=${CMAKE_OBJCOPY} OBJDUMP=${CMAKE_OBJDUMP} CFLAGS=${PROOT_C_FLAGS} LDFLAGS=${PROOT_LINKER_FLAGS}
        INSTALL_COMMAND cd ${PROOT_SRC} && cp -f ./proot ${CMAKE_BINARY_DIR}/proot
        DEPENDS talloc unwind_ptrace
        BUILD_IN_SOURCE 0
    )
    
    # Make the proot binary available
    set(PROOT_BINARY ${CMAKE_BINARY_DIR}/proot)
    set(PROOT_TARGET proot-termux)
else()
    message(FATAL_ERROR "ProotTermux.cmake is only for Android/Termux builds. Use Android NDK toolchain.")
endif()
