# This file was generated by AI and is not subject to copyright protection.
# It is dedicated to the public domain.

# CMake configuration for building proot for standalone Linux server

include(ExternalProject)

# Check if we're building for Android or Linux
if(ANDROID)
    # Use the Android-specific Proot.cmake
    include(Proot)
else()
    # Build proot for native Linux
    
    # Find or build talloc
    find_library(TALLOC_LIBRARY talloc)
    find_path(TALLOC_INCLUDE_DIR talloc.h)
    
    if(NOT TALLOC_LIBRARY OR NOT TALLOC_INCLUDE_DIR)
        message(STATUS "talloc not found, will build from source")
        include(Talloc)
        set(TALLOC_INCLUDE_DIRS ${TALLOC_INCLUDE_DIR})
        set(TALLOC_LIBRARIES ${TALLOC_LIBRARY})
    else()
        message(STATUS "Found talloc: ${TALLOC_LIBRARY}")
        set(TALLOC_INCLUDE_DIRS ${TALLOC_INCLUDE_DIR})
        set(TALLOC_LIBRARIES ${TALLOC_LIBRARY})
    endif()
    
    set(PROOT_SRC ${CMAKE_CURRENT_BINARY_DIR}/proot-prefix/src/proot/src)
    set(PROOT_BIN ${CMAKE_CURRENT_BINARY_DIR}/proot-prefix/src/proot-build)
    
    # Use system compiler for native build
    set(PROOT_C_FLAGS "-I${TALLOC_INCLUDE_DIRS} -I${PROOT_SRC} -D_GNU_SOURCE")
    set(PROOT_LINKER_FLAGS "-L${CMAKE_BINARY_DIR} -ltalloc")
    
    ExternalProject_Add(
        proot-native
        GIT_REPOSITORY https://github.com/Ananbox/proot.git
        GIT_TAG a8189b1e6fb892104fdc01a939c7e75e9325a3c0
        GIT_SHALLOW 1
        CONFIGURE_COMMAND cd ${PROOT_SRC} && make clean || true
        BUILD_COMMAND cd ${PROOT_SRC} && make V=1 CFLAGS=${PROOT_C_FLAGS} LDFLAGS=${PROOT_LINKER_FLAGS}
        INSTALL_COMMAND cd ${PROOT_SRC} && cp -f ./proot ${CMAKE_BINARY_DIR}/proot
        BUILD_IN_SOURCE 0
    )
    
    # Make the proot binary available
    set(PROOT_BINARY ${CMAKE_BINARY_DIR}/proot)
endif()
