/*
 * This file was generated by AI and is not subject to copyright protection.
 * AI-generated content is not applicable for copyright.
 */
package com.github.ananbox

import android.os.Bundle
import android.view.MenuItem
import android.widget.ScrollView
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import java.io.File

class LogViewActivity : AppCompatActivity() {

    private companion object {
        // Maximum log file size to read (1MB)
        private const val MAX_LOG_SIZE = 1024 * 1024L
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_log_view)
        supportActionBar?.setDisplayHomeAsUpEnabled(true)
        supportActionBar?.setTitle(R.string.settings_logs_title)

        val logTextView = findViewById<TextView>(R.id.log_text_view)
        val scrollView = findViewById<ScrollView>(R.id.log_scroll_view)

        val logContent = StringBuilder()

        // Read proot.log from internal storage
        val prootLogFile = File(filesDir, "proot.log")
        if (prootLogFile.exists()) {
            logContent.append("=== proot.log ===\n")
            logContent.append(readLogFile(prootLogFile))
            logContent.append("\n\n")
        }

        // Read system.log from rootfs/data
        val systemLogFile = File(filesDir, "rootfs/data/system.log")
        if (systemLogFile.exists()) {
            logContent.append("=== system.log ===\n")
            logContent.append(readLogFile(systemLogFile))
            logContent.append("\n\n")
        }

        if (logContent.isEmpty()) {
            logContent.append(getString(R.string.settings_logs_empty))
        }

        logTextView.text = logContent.toString()

        // Scroll to bottom to show most recent logs
        scrollView.post {
            scrollView.fullScroll(ScrollView.FOCUS_DOWN)
        }
    }

    private fun readLogFile(file: File): String {
        return if (file.length() > MAX_LOG_SIZE) {
            // For large files, read only the last MAX_LOG_SIZE bytes using RandomAccessFile
            java.io.RandomAccessFile(file, "r").use { raf ->
                raf.seek(file.length() - MAX_LOG_SIZE)
                // Skip to next newline to avoid partial line
                raf.readLine()
                val remainingSize = file.length() - raf.filePointer
                // Safety check to prevent integer overflow
                if (remainingSize > MAX_LOG_SIZE || remainingSize < 0) {
                    return@use "[...truncated - file too large...]\n"
                }
                val remaining = ByteArray(remainingSize.toInt())
                raf.readFully(remaining)
                "[...truncated...]\n" + String(remaining, Charsets.UTF_8)
            }
        } else {
            file.readText()
        }
    }

    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        return when (item.itemId) {
            android.R.id.home -> {
                finish()
                true
            }
            else -> super.onOptionsItemSelected(item)
        }
    }
}
